/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tuannvm/r53-operator/apis/route53/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRoute53s implements Route53Interface
type FakeRoute53s struct {
	Fake *FakeRoute53V1alpha1
}

var route53sResource = schema.GroupVersionResource{Group: "route53.tuannvm.com", Version: "v1alpha1", Resource: "route53s"}

var route53sKind = schema.GroupVersionKind{Group: "route53.tuannvm.com", Version: "v1alpha1", Kind: "Route53"}

// Get takes name of the route53, and returns the corresponding route53 object, and an error if there is any.
func (c *FakeRoute53s) Get(name string, options v1.GetOptions) (result *v1alpha1.Route53, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(route53sResource, name), &v1alpha1.Route53{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Route53), err
}

// List takes label and field selectors, and returns the list of Route53s that match those selectors.
func (c *FakeRoute53s) List(opts v1.ListOptions) (result *v1alpha1.Route53List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(route53sResource, route53sKind, opts), &v1alpha1.Route53List{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.Route53List{ListMeta: obj.(*v1alpha1.Route53List).ListMeta}
	for _, item := range obj.(*v1alpha1.Route53List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested route53s.
func (c *FakeRoute53s) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(route53sResource, opts))
}

// Create takes the representation of a route53 and creates it.  Returns the server's representation of the route53, and an error, if there is any.
func (c *FakeRoute53s) Create(route53 *v1alpha1.Route53) (result *v1alpha1.Route53, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(route53sResource, route53), &v1alpha1.Route53{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Route53), err
}

// Update takes the representation of a route53 and updates it. Returns the server's representation of the route53, and an error, if there is any.
func (c *FakeRoute53s) Update(route53 *v1alpha1.Route53) (result *v1alpha1.Route53, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(route53sResource, route53), &v1alpha1.Route53{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Route53), err
}

// Delete takes name of the route53 and deletes it. Returns an error if one occurs.
func (c *FakeRoute53s) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(route53sResource, name), &v1alpha1.Route53{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRoute53s) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(route53sResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.Route53List{})
	return err
}

// Patch applies the patch and returns the patched route53.
func (c *FakeRoute53s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Route53, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(route53sResource, name, data, subresources...), &v1alpha1.Route53{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Route53), err
}
