apiVersion: route53.tuannvm.com/v1alpha1
kind: Route53
metadata:
  name: sample-route53
spec:
  type: CNAME
  routingPolicy: Weighted
  name: sample
  domain: sandbox.honestbee.com
  records:
    sample1.sandbox.honestbee.com: 50
    sample2.sandbox.honestbee.com: 50
  ttl: 60
