apiVersion: route53.tuannvm.com/v1alpha1
kind: Route53
metadata:
  name: sample-route53
spec:
  type: CNAME
  routingPolicy: Weighted
  name: sample
  domain: example.com
  records:
    sample1.example.com: 50
    sample2.example.com: 50
  ttl: 60
